### Install Package  😈
---

In [1]:
import numpy as np
import gym
import random

### Créer la env 🛋
---
- Here we'll create the FrozenLake environment.
- OpenAI Gym is a library composed of many environments that we can use to train our agents.
- In our case we choose to use Frozen Lake.

In [2]:
env = gym.make("FrozenLake-v0")

### Créer la Q-Table 📜
---
- Now, we'll create our Q-table, to know how much rows (states) and columns (actions) we need, we need to calculate the action_size and the state_size
- OpenAI Gym provides us a way to do that: env.action_space.n and env.observation_space.n


In [12]:
# C'est cols
action_size = env.action_space.n

# C'est rows
state_size = env.observation_space.n

# Créer la Q-table:
qtable = np.zeros((state_size, action_size))
print(qtable)

action_size =  4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Créer la parameters:
---


In [4]:
total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob

### Créer la code de simulation:
---

<img src="image/01_g_learning_algorithm.png"> 
<br>

In [ ]:
# List of rewards
rewards = []

# 2 Loop tout episodes:
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    

### JA_Test
---

In [17]:
rows_size = int(10) # states
cols_size = int(4)  # actions

check_my_np = np.zeros((rows_size,cols_size))
check_my_np

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
check_my_np[9][3]

0.0